"""Add is_default field to Deck (nullable)

Revision ID: 1c5b764cd2ee
Revises: a331d312018e
Create Date: 2025-03-05 00:50:07.204840

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c5b764cd2ee'
down_revision = 'a331d312018e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('decks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_default', sa.Boolean(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('decks', schema=None) as batch_op:
        batch_op.drop_column('is_default')

    # ### end Alembic commands ###
