"""removes default value column

Revision ID: a331d312018e
Revises: a71d6f87869c
Create Date: 2025-03-04 13:23:59.832627

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a331d312018e'
down_revision = 'a71d6f87869c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('decks', schema=None) as batch_op:
        batch_op.drop_column('is_default')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('decks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_default', sa.BOOLEAN(), nullable=True))

    # ### end Alembic commands ###
