"""added default decks

Revision ID: d1857a907548
Revises: 1c5b764cd2ee
Create Date: 2025-03-05 18:40:42.697149

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1857a907548'
down_revision = '1c5b764cd2ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('default_decks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('subject', sa.String(length=50), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('difficulty', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('default_flashcards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('default_deck_id', sa.Integer(), nullable=False),
    sa.Column('front_text', sa.Text(), nullable=False),
    sa.Column('back_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['default_deck_id'], ['default_decks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_default_decks',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('default_deck_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['default_deck_id'], ['default_decks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'default_deck_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_default_decks')
    op.drop_table('default_flashcards')
    op.drop_table('default_decks')
    # ### end Alembic commands ###
